export const list = [
  {
    title: '기초 알고리즘',
    path: '1',
    items: [
      'vector',
      'stack',
      'queue',
      'deque',
      'sort',
      'binary_search',
      'prefix_sum',
      'two_pointer',
      'set',
      'map',
      'priority_queue',
      'primality_test',
      'sieve_of_eratosthenes',
      'euclidean',
      'exponentiation_by_squaring',
      'backtracking',
      'dfs',
      'bfs',
    ],
  },
  {
    title: '중급 알고리즘',
    path: '2',
    items: [
      'dsu',
      'sweeping',
      'dijkstra',
      'bellman-ford',
      'spfa',
      'floyd-warshall',
      'kahn',
      'kruskal',
      'segment_tree',
      'fenwick_tree',
      'dynamic_segment_tree',
      'tsp',
      'modular_multiplicative_inverse',
      'trie',
      'kmp',
      'rabin-karp',
      'ccw',
      'line_intersection',
      'offline_query',
    ],
  },
  {
    title: '고급 알고리즘',
    path: '3',
    items: [
      'pbds',
      'rope',
      'walking_on_segment_tree',
      'segment_tree_with_lazy_propagation',
      'merge_sort_tree',
      'sparse_segment_tree',
      'hld',
      'tarjan',
      '2-sat',
      'kuhn',
      'edmonds-karp',
      'mcmf',
      'dinic',
      'hopcroft-karp',
      'aho-corasick',
      'imos',
      'square_root_decomposition',
      'mo',
      'pbs',
      'graham_scan',
      'point_in_convex_polygon',
      'rotating_calipers',
      'deque_trick',
      'cht',
    ],
  },
] as const